name: Deploy 

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create versioned directory
      run: |
        VERSION=${{ github.ref_name }}
        SITE="./public/v${VERSION}"
        mkdir -p "$SITE"
        files_to_copy=("en" "ru" "index.html")
        for file in "${files_to_copy[@]}"; do
          cp -r "./${file}" "$SITE/"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        keep_files: true
